# Hexo Configuration
## Docs: http://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: FEYehのBlog
subtitle: I have no special talent. I am only passionately curious.
description: FEYehのBlog
author: FEYeh
language: zh-Hans
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://ebooks4coding.com 
root: / 
permalink: :title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 7
pagination_dir: page

# Extensions
## Plugins: http://hexo.io/plugins/
## Themes: http://hexo.io/themes/
theme: melody
Plugins: 
  - hexo-generator-feed
  - hexo-algoliasearch
feed: 
  type: atom
  path: atom.xml
  limit: 20

algolia: 
  appId: "7SER0HTVYZ"
  apiKey: "b8e786caffbbee124ee8651ed7c103ea"
  adminApiKey: "de2574761ffbb28826e97bbebd58cca6"
  chunkSize: 5000
  indexName: "myblog"
  fields:
    - content:strip:truncate,0,500
    - excerpt:strip
    - gallery
    - permalink
    - photos
    - slug
    - tags
    - title

# Deployment
## Docs: http://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: git@github.com:FEYeh/FEYeh.github.io.git 
  branch: master

sitemap:
  path: sitemap.xml

# Optimize
## Optimize
  # Defaults
  css_concat: true
  css_min: true
  js_concat: true
  js_min: true
  html_min: true
  gzip: true

all_minifier: true

css_minifier:
  enable: true
  exclude: 
    - '*.min.css'
js_minifier:
  enable: true
  mangle: true
  exclude: 
    - '*.min.js'
image_minifier:
  enable: false

offline:
  maximumFileSizeToCacheInBytes: 10485760
  staticFileGlobs:
    - public/**/*.{js,html,css,png,jpg,jpeg,gif,svg,json,xml}
  stripPrefix: public
  verbose: true
  runtimeCaching:
    # CDNs - should be cacheFirst, since they should be used specific versions so should not change
    - urlPattern: /*
      handler: cacheFirst
      options:
        origin: cdnjs.cloudflare.com
    - urlPattern: /*
      handler: cacheFirst
      options:
        origin: cdn.jsdelivr.net
    - urlPattern: /*
      handler: cacheFirst
      options:
        origin: unpkg.com 
    - urlPattern: /*
      handler: cacheFirst
      options:
        origin: fonts.googleapis.com
    - urlPattern: /*
      handler: cacheFirst
      options:
        origin: fonts.gstatic.com
    - urlPattern: /*
      handler: cacheFirst
      options:
        origin: cdnjs.cloudflare.com
    - urlPattern: /*
      handler: cacheFirst
      options:
        origin: cdn.bootcss.com
    - urlPattern: /*
      handler: cacheFirst
      options:
        origin: ebooks4coding.com
    - urlPattern: /*
      handler: cacheFirst
      options:
        origin: ws1.sinaimg.cn 

